### PR TITLE
additional documents.

### PR DESCRIPTION
**Pull request by BrettLMiller**
Other relevant documents, some later updates on API changes are real gems.

### CODE REVIEW

**Review by justinmassiot — COMMENTED** [review]
Thank you @BrettLMiller for your valuable additions!

I suppose the following files are extracted from website pages:  `System API Low Level Routines - (2017-02-15).pdf`, `Technical Reference - PCB APIUpdates - (2016-09-26).pdf`. Are the pages still live?

In this `scripting-reference` repo, I try to archive only official documents that used to be provided by Altium.
About the document written by Jelle Laarman `AdvancedScripting_OutputJobs_0R1 - (2016-02-17).pdf`, I suggest that we add it in the [scripts-libraries](https://github.com/Altium-Designer-addons/scripts-libraries) repository.
As for `Layer+Stack-Object.htm`, is it a document you produced yourself?

**Comment by BrettLMiller** [comment]
I think the last generation online help webpages are still up. For how much longer, who can say.
I did not download them into pdf, I scraped them from Altium's website.
I struggle to see the new format of scripting documentation can help anyone.

The Layer+Stack-Object.htm was scraped from the AD forums.
Rob Evans Altium March 2014.
https://forum.live.altium.com/#/posts/203565/559901

**Comment by justinmassiot** [comment]
I've just added your 2 documents there: https://github.com/Altium-Designer-addons/scripts-libraries/tree/master/Documentation%20(unofficial)
I've converted the HTML page into an ODT document, to ease a future modification.

I think the following pages are not less usable than the previous "techdocs" version:
https://www.altium.com/documentation/altium-designer/system-api-low-level-routines
https://www.altium.com/documentation/altium-designer/technical-reference-pcb-api
But if you want, I propose to also add your PDFs to the `scripts-libraries/` repository.

Finally, I'm not sure `TU0130 Getting Started with the C-to-Hardware Compiler` has something to do with scripting. Does it? (What about TR0173?)

If I summarize, may you please remove the following 5 (6?) items in order to keep only relevant official documentation? Thus, I could merge your branch directly.

- AdvancedScripting_OutputJobs_0R1 - (2016-02-17).pdf
- Layer+Stack-Object.htm
- System API Low Level Routines - (2017-02-15).pdf
- Technical Reference - PCB APIUpdates - (2016-09-26).pdf
- TU0130 Getting Started with the C-to-Hardware Compiler -(2008-05-16).pdf
- ? TR0173 C Language Reference - v4.0 - (2009-04-06).pdf ?

Thank you.

**Comment by BrettLMiller** [comment]
I have done as you asked; deleted the 6 files.

**Pull request merged**
